version: '3'

services:
  lumen:
    restart: 'always'
    image: php:7.4
    command: php -S 0.0.0.0:8000 -t /app/public
    ports:
      - "8000:8000"
    volumes:
      - ./lumen:/app
    depends_on:
      - mysql
      - composer
    links:
      - mysql

  composer:
    restart: 'no'
    image: composer/satis
    command: install
    volumes:
      - ./lumen:/app
  
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lumen

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8010:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysqldata:
    driver: local
