version: '3'

services:
  lumen:
    restart: 'always'
    build: ./lumen
    ports:
      - "8000:8000"
    working_dir: /var/www
    volumes:
      - ./lumen:/var/www
    depends_on:
      - mysql
      - composer
    links:
      - mysql
    networks:
      - lumen-database

  composer:
    restart: 'no'
    image: composer/satis
    command: install
    volumes:
      - ./lumen:/var/www
  
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lumen
    networks:
      - lumen-database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8010:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - lumen-database

volumes:
  mysqldata:
    driver: local

networks:
  lumen-database:
    driver: bridge
